# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('company_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=40)),
                ('liscom_code', models.CharField(default=0, max_length=6)),
                ('company_address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('introduction', models.CharField(max_length=500)),
                ('website', models.CharField(max_length=100, null=True)),
                ('img_address', models.CharField(max_length=100, null=True)),
                ('intro_address', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='evaluator',
            fields=[
                ('evaluator_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('evaluator_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='industry',
            fields=[
                ('industry_id', models.IntegerField(choices=[(1, '农林牧渔业'), (2, '采矿业'), (3, '制造业'), (4, '住宿和餐饮业'), (5, '金融业'), (6, '房地产业'), (7, '租赁和商务服务'), (8, '电力、燃气及水的生产和供应'), (9, '建筑业'), (10, '水利、环境和公共设施管理'), (11, '居民服务和其他服务'), (12, '教育'), (13, '信息传输、计算机服务和软件业'), (14, '卫生、社会保障和社会福利'), (15, '文化、体育和娱乐业'), (16, '公共管理和社会组织'), (17, '国际组织'), (18, '科学研究、技术服务和地质勘查'), (19, '交通运输、仓储和邮政'), (20, '批发和零售')], primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=50)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='interval',
            fields=[
                ('interval_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('interval_1', models.IntegerField()),
                ('interval_2', models.IntegerField()),
                ('interval_3', models.IntegerField()),
                ('interval_4', models.IntegerField()),
                ('interval_5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='junior_index',
            fields=[
                ('junior_index_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('junior_index_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
                ('evaluator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.evaluator')),
            ],
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('period_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='senior_index',
            fields=[
                ('senior_index_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('senior_index_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=6, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('user_type', models.IntegerField(choices=[(0, '临时用户'), (1, '用户'), (2, '超级用户')])),
                ('user_authority', models.IntegerField(null=True)),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.company')),
            ],
        ),
        migrations.AddField(
            model_name='junior_index',
            name='period_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.period'),
        ),
        migrations.AddField(
            model_name='junior_index',
            name='senior_index_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.senior_index'),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.industry'),
        ),
    ]
