# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-02 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0002_auto_20171227_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='val_res',
            name='user_id',
            field=models.ForeignKey(default=20171031000, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.users'),
            preserve_default=False,
        ),
    ]
