# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0003_val_res_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='val_res',
            name='evaluator_res',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='val_res',
            name='period_res',
            field=models.TextField(max_length=1000),
        ),
    ]
