# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0004_auto_20180104_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='val_res',
            name='senior_res',
            field=models.TextField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
