# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0007_val_res_val_model_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='val_res',
            name='final_res',
            field=models.CharField(max_length=12),
        ),
    ]
