# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-16 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0008_auto_20180104_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='def_index',
            fields=[
                ('junior_index_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('junior_index_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
                ('evaluator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.evaluator')),
                ('period_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.period')),
                ('senior_index_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.senior_index')),
            ],
        ),
    ]
