# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0009_def_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='def_evaluator',
            fields=[
                ('evaluator_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('evaluator_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='def_period',
            fields=[
                ('period_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('period_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='def_senior_index',
            fields=[
                ('senior_index_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('senior_index_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='def_index',
            name='evaluator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.def_evaluator'),
        ),
        migrations.AlterField(
            model_name='def_index',
            name='period_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.def_period'),
        ),
        migrations.AlterField(
            model_name='def_index',
            name='senior_index_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evasysapp.def_senior_index'),
        ),
    ]
