# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0012_def_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='def_index',
            old_name='def_junior_index',
            new_name='evaluator_name',
        ),
        migrations.RenameField(
            model_name='def_index',
            old_name='def_index_id',
            new_name='junior_index_id',
        ),
        migrations.RenameField(
            model_name='def_index',
            old_name='def_senior_index',
            new_name='junior_index_name',
        ),
        migrations.RenameField(
            model_name='def_index',
            old_name='evaluator',
            new_name='period_name',
        ),
        migrations.RenameField(
            model_name='def_index',
            old_name='period',
            new_name='senior_index_name',
        ),
    ]
