# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evasysapp', '0013_auto_20180118_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='def_senior_index',
            fields=[
                ('senior_index_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('senior_index_name', models.CharField(max_length=30, unique=True)),
                ('memo', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
